### PR TITLE
39 documentation githubguidelines

### PR DESCRIPTION
**Pull request by mathiaszinnen**

### CODE REVIEW

**Comment by mathiaszinnen** [comment]
@andreas-bauer @dirkriehle I added you just in case you want to be involved, but please don't feel obliged to react.

**Comment by andreas-bauer** [comment]
I changed the wording a little bit.

**Review by andreas-bauer — APPROVED** [review]
Looks good to me.

**Comment by georg-schwarz** [comment]
Thanks guys for the nice discussion! I like the solution we have now very much :)

**Pull request merged**
