### PR TITLE
Adapter: refactor the configuration

### PR DESCRIPTION
**Pull request by sonallux**
- refactor the handling of configuration by using spring boot's `ConfigurationProperties` instead of `System.getenv(...)`
- remove useless annotations and code
- refactor all `System.{err|out}.println(...)` calls to use a real `Logger`
- add [lombok](https://projectlombok.org) to reduce boilerplate code

### CODE REVIEW

**Review by georg-schwarz — DISMISSED** [review]
nice!

**Comment by sonallux** [comment]
@georg-schwarz and @lunedis are you ok if I add [lombok](https://projectlombok.org) to the adapter? With lombok we can get rid of a lot of boilerplate code (getter, setter, constructors, ...) by just adding an annotation.

**Comment by georg-schwarz** [comment]
Yeah, I'd appreciate less clutter in our java code base. What do you think @lunedis ?

**Comment by lunedis** [comment]
Lombok looks interesting, no objections from me for using it.

**Comment by sonallux** [comment]
I have added lombok and now we have ~500 lines less in the adapter code base 🚀

**Comment by georg-schwarz** [comment]
Awesome! Much cleaner now!

**Review by georg-schwarz — APPROVED** [review]

**Pull request merged**
