### PR TITLE
Make storage-mq rabbitmq connection durable

### LINKED ISSUE #174: storage-mq crashes at startup
The storage-mq crashes at startup. The exception thrown hints at the durable argument for ods_global exchange.

### PR DESCRIPTION
**Pull request by mathiaszinnen**
closes #174

### CODE REVIEW

**Comment by mathiaszinnen** [comment]
Included in #178

**Review by sonallux — COMMENTED** [review]
LGTM

But I think it's too late as you have already closed this PR :/

**Comment by sonallux** [comment]
Maybe you can reopen this PR, so we can get this bug fixed faster.

**Comment by mathiaszinnen** [comment]
I combined it with the other pr to have a running branch to merge into master

**Pull request closed without merging**
