### PR TITLE
Remove auth service

### PR DESCRIPTION
**Pull request by sonallux**
- [x] Adapt the notification and transformation service to not require the auth service.
- [x] Remove authentication from the ui
- [x] Remove auth service

### CODE REVIEW

**Comment by georg-schwarz** [comment]
Maybe it makes sense to remove the auth implementation on ui and replace it with a mock that fakes always logged in behavior? Not sure though..

**Comment by sonallux** [comment]
> Maybe it makes sense to remove the auth implementation on ui and replace it with a mock that fakes always logged in behavior? Not sure though..

I have removed all keycloak implementation details from the ui and added a mock that fakes authentication to always be logged in.

**Comment by georg-schwarz** [comment]
Opened a PR for minor changes since I don't have write access to your repo. Good job! ;-)

**Comment by sonallux** [comment]
@georg-schwarz I have merged your MR and fixed another missing await

**Review by georg-schwarz — APPROVED** [review]

**Pull request merged**
