### PR TITLE
Adapter: Refactor response status

### PR DESCRIPTION
**Pull request by sonallux**
This PR fixes the second part of #156. Now meaningful HTTP status codes are returned from the REST endpoints of the Adapter.

### CODE REVIEW

**Review by georg-schwarz — DISMISSED** [review]

**Comment by MBuchalik** [comment]
Is there any particular reason why the string "LOL" is being used here so often? Doesn't really sound professional to me, tbh ;) But I haven't yet worked with the ODS code, so there might be a simple explanation :)

(I saw that the string was being used before as well. So I am curious about the "why" :D)

**Comment by sonallux** [comment]
> Is there any particular reason why the string "LOL" is being used here so often? Doesn't really sound professional to me, tbh ;) But I haven't yet worked with the ODS code, so there might be a simple explanation :)
> 
> (I saw that the string was being used before as well. So I am curious about the "why" :D)

`LOL` is actually only used in the test cases for validating that an unsupported input is rejected. But any other non-valid string could be used instead too. So I think there is no real reason why `LOL` is used.

I personally have just copied what others did before, I was just too lazy to come up with something new :D

**Comment by MBuchalik** [comment]
Alright, thanks for the explanation :)

**Comment by georg-schwarz** [comment]
Well, maybe we should use more serious terms.. 😅 Should we change it to something more professional?

Some suggestions: "NOT-SUPPORTED", "NULL", ...

**Comment by sonallux** [comment]
I have replaced all the `LOLs` with something meaningful. This would also make @andreas-bauer happy that I am following the Boy Scout Rule 🤪

**Review by georg-schwarz — APPROVED** [review]

**Pull request merged**
