### PR TITLE
Update node-dry-pg

### PR DESCRIPTION
**Pull request by sonallux**
Updates the `node-dry-pg` library for all services to `1.0.0-alpha1`. This will make all services more tolerant to database connection losses (see jvalue/node-dry-pg#2).

This PR also introduces the `node-dry-basic` and `node-dry-pg` library to the StorageMQ service, as this has not yet been done.

### CODE REVIEW

**Comment by sonallux** [comment]
@georg-schwarz I have not found any issues in the `1.0.0-alpha1` version of the `node-dry-pg` library. So you can do a `1.0.0` release of `node-dry-pg`.

**Comment by georg-schwarz** [comment]
Thanks @sonallux
Version `1.0.0` should be available now!

**Comment by sonallux** [comment]
> Version `1.0.0` should be available now!

Nice, thanks. I have already updated the PR to use version `1.0.0` 🚀

**Review by georg-schwarz — APPROVED** [review]
Nice!

**Pull request merged**
