### PR TITLE
Fix faulty mocking in provider-side CDC-Test of Pipeline

### PR DESCRIPTION
**Pull request by felix-oq**
This PR fixes faulty mocking that was present in the provider-side CDC-Test. The mocked behaviour of `PipelineConfigManager` for updating and deleting pipelines did not match its actual behavior in cases where there is no pipeline with the requested id.

In order to fix that problem, I modified the interactions between UI and Pipeline to ease the implementation of the mock. In particular for updating/deleting, the `PipelineConfigManager` now returns `undefined` if a pipeline with the given id does not exist and returns the updated/deleted pipeline if it exists.
Due to these interaction changes, a unit test and some integration and system tests had to be adjusted.

### CODE REVIEW

**Comment by georg-schwarz** [comment]
Saw you changed response codes in some cases. What should be the case for deletion and update on unknown element? Just to have it consistent..

**Comment by felix-oq** [comment]
> Saw you changed response codes in some cases. What should be the case for deletion and update on unknown element? Just to have it consistent..

For updating or deleting pipelines with an existing id, I changed the response codes from `204` to `200` because the responses now have a body that contains the updated/deleted pipeline.  `204` doesn't fit in this case anymore because the response now has content in its body.

For trying to update a pipeline with a non-existent id, I kept the `404` status code because the update operation cannot be performed when the pipeline to update is not present.

For trying to delete a pipeline with a non-existent id, I kept the response code `204` because the operation still ensures that there remains no pipeline with the given id, even though no deletion has to be performed. In that case, the body of the response remains empty because there is no pipeline to delete. The empty content of the response is resembled by the `204` status code which also makes it possible for the client to distinguish the two cases (`200` with an actual pipeline deletion and `204` where the pipeline wasn't present in the first place).

**Comment by georg-schwarz** [comment]
Discussion outsourced to https://github.com/jvalue/ods/issues/388

**Comment by georg-schwarz** [comment]
I think we will go with 404 in cases of a non-existing entity.

**Review by georg-schwarz — APPROVED** [review]

**Review by georg-schwarz — APPROVED** [review]

**Pull request merged**
