### PR TITLE
Cleanup traefik labels in docker-compose.yml

### PR DESCRIPTION
**Pull request by sonallux**
Currently, only some of our microservices are defining the `traefik.http.services.<service-name>.loadbalancer.server.port=<port>` label. According to the [Traefik documentation](https://doc.traefik.io/traefik/providers/docker/#port-detection), this label is not required when the container is exposing exactly one port. As all services expose only one port (see the `EXPOSE` statement in the `Dockerfile`s), I would remove this label everywhere.

The RabbitMQ management UI is currently accessible directly via `localhost:15672`. And there is a traefik route `/api/amqp` configured too, which I have fixed to use the correct port. 

But actually, I think that we should not expose the RabbitMQ Management UI under `/api/amqp` as it is only for administration purposes. Therefore I would like to remove exposing it under `/api/amqp`. What do you think? @georg-schwarz @mathiaszinnen @lunedis If you are ok with that I am going to update this PR.

### CODE REVIEW

**Comment by georg-schwarz** [comment]
Thanks for removing the unnecessary clutter! 

For the management console, I don't see pressure removing it since it should be password protected. However, I don't think it is used at all, right? If so, we can also remove it I guess...

**Comment by sonallux** [comment]
> However, I don't think it is used at all, right?

The RabbitMQ Managemnt UI is quite useful for debugging AMQP messages and manually sending messages. But I always use it directly via `localhost:15672`.

---

Another question. What is this service doing? It can not be accessed from the outside, because it does not have a `ports` mapping.
```
  storage-swagger: # API documentation for storage service
    image: swaggerapi/swagger-ui
    environment:
      API_URL: http://localhost:9400/
```

**Comment by sonallux** [comment]
How about comment this service out, as it is just for managing Postgres? If anyone wants to use it he can uncomment it.
```
  storage-db-ui: # management UI for Postgres
    image: adminer
    ports:
      - 8080:8080
```

**Comment by mathiaszinnen** [comment]
> The RabbitMQ management UI is currently accessible directly via `localhost:15672`. And there is a traefik route `/api/amqp` configured too, which I have fixed to use the correct port.
> 
> But actually, I think that we should not expose the RabbitMQ Management UI under `/api/amqp` as it is only for administration purposes. Therefore I would like to remove exposing it under `/api/amqp`. What do you think? @georg-schwarz @mathiaszinnen @lunedis If you are ok with that I am going to update this PR.

As long as we still expose it directly, we should remove the API route, yes. 

I think I introduced it for debugging, did not manage to make it work via traefik, switched to exposing the port directly and forgot to remove it afterwards. So thanks for finding it!

**Comment by georg-schwarz** [comment]
Ok, so I think the RabbitMQ Management UI should have no use in production I guess, so we can remove that port in Traefik.

The swagger thing is deprecated and can be removed. Although, on the long run we want to have a fully working swagger-ui for the whole API.

The adminer can be commented out, but should also be renamed. It's just for debugging.

**Comment by lunedis** [comment]
I'm currently working on #238. Good to know that you want to comment out certain services, then I don't have to handle those there.

**Comment by sonallux** [comment]
I have updated my PR:
- Remove RabbitMQ Management UI from traefik. It is still accessible on `localhost:15672`
- Remove `storage-swagger` service
- Comment out `adminer` service

Now two fewer services have to be started 🚀

**Review by georg-schwarz — APPROVED** [review]

**Review by mathiaszinnen — APPROVED** [review]

**Pull request merged**
